apiVersion: v1
kind: Secret
metadata:
  name: app-aws-secret
type: Opaque
data:
  credentials: QVdTX0FDQ0VTU19LRVlfSUQgPSBBS0lBWFFJUUFCM0dTNzNVSUVXTApBV1NfU0VDUkVUX0FDQ0VTU19LRVkgPSBBSXN4b3Nkem11UWRaZUhLU3M3NTc4S1U0NldKbjhtREtFOTBZMVY1