apiVersion: v1
kind: Secret
metadata:
  name: app-aws-secret
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = AKIA4J7PFWW4NZE425EP
    aws_secret_access_key = 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

